debug: false
content_visibility: true
navbar:
  logo: https://cdn.jsdelivr.net/gh/612901/661111@main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-12-21%20102358.png # choose [img] or [icon + title]
  img: 'https://cdn.jsdelivr.net/gh/612901/661111@main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-12-21%20102358.png' # volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png
  icon:
  title: '无影博客'
  menu:
    - name: 分类
      icon: fa-fw iconfont icon-fenlei1
      rows:  
        - name: gridea
          icon: fa-fw iconfont icon-fenlei1
          url: tags/gridea/
        - name: bilbil
          icon: fa-fw iconfont icon-fenlei1
          url: tags/blibli/
        - name: 学科
          icon: fa-fw iconfont icon-fenlei1
          url: tags/学科/ 
        - name: bilbilpage2
          icon: fa-fw iconfont icon-fenlei1
          url: tags/blibli-page-2/
        - name: 相册集
          icon: fa-fw iconfont icon-fenlei1
          url: tags/相册/     
    - name: 归档
      icon: fa-fw iconfont icon-bendiwenjianjia
      url: archives/
    - name: 社交
      icon: fas fa-bars
      rows:
        - name: 友链
          icon: fa-fw iconfont icon-lianjie
          url: friends/
        - name: 朋友圈
          icon: fa-fw iconfont icon-pengyouquan
          url: links/
        - name: 开往
          icon: fas fa-link
          url: https://travellings.link/
    - name: 关于
      icon: fas fa-user
      rows:
        - name: 版权声明
          url: 2022/09/17/copyright/
        - name: 免责声明
          url: 2022/09/17/mian-ze-sheng-ming-1/
        - name: 关于本站
          url: 2022/09/24/list/
        - name: 关于
          url: /2022/08/20/about/
        - name: 我的项目
          icon: fas fa-user
          rows:
             - name: musicapi
               icon: fa-fw iconfont icon-jiankong
               url: https://api.wyblog.repl.co
             - name: alist
               icon: fa-light fa-folder-open TURQUOISE faa-vertical
               rows:
                 - name: 1
                   url: https://alist.661111.repl.co/
                 - name: 2
                   url: https://alist-replit-2.661111.repl.co/
             - name: 朋友圈api
               icon: fas fa-user-group
               url: https://wyblog.eu.org
             - name: musicapi
               icon: fas fa-music
               rows:
                 - name: gridea博客
                   icon: fas fa-tags
                   rows:
                     - name: 1
                       icon: fas fa-tags
                       url: https://timely-griffin-781b87.netlify.app
                     - name: 2
                       icon: fas fa-tags
                       url: https://661111.github.io 
                 - name: 博客镜像
                   icon: fas fa-tags
                   rows:
                     - name: 1
                       icon: fas fa-tags
                       url: https://effulgent-kringle-368d41.netlify.app/
                     - name: 2
                       icon: fas fa-tags
                       url: https://wyblog1.eu.org
    - name: 更多
      icon: fa-solid fa-ellipsis-v
      rows:
        - name: 深色模式
          icon: fa-light fa-moon POMEGRANATE faa-vertical
          toggle: darkmode
        - name: 背景音乐
          icon: fa-fw iconfont icon-jiankong
        - name: hr        
        - name: 音乐盒
          icon: fas fa-music
          url: https://api.wyblog.repl.co
        - name: 哔哩哔哩
          icon: fa-solid fa-comment fa-fw 
          rows:
             - name: 1
               icon: fa-light fa-folder-open TURQUOISE faa-vertical
               url: tags/blibli/
             - name: 2
               icon: fa-light fa-folder-open TURQUOISE faa-vertical
               url: tags/blibli-page-2/           
        - name: 说说
          icon: fa-fw iconfont icon-shejiao
          url: shuoshuo/
        - name: 追番页
          icon: fa-solid fa-comment fa-fw 
          rows:
             - name: 1
               icon: fa-light fa-folder-open TURQUOISE faa-vertical
               url: bangumis/
site_footer:
  layout: [aplayer, social, source, analytics, copyright]
  copyright: '[Copyright © Since 2017 Volantis Team](https://github.com/volantis-x/)'
  social:
    - img: volantis-static/media/org.volantis/icon/1322024-social-media/029-github.svg
      url: https://github.com/612901/

      
  message:
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_style/_plugins/fontcolor.styl
      default: fa-solid fa-info-circle light-blue
      quection: fa-solid fa-question-circle light-blue
    time:     # 默认持续时间
      default: 5000
      quection: 20000
    position: 'topRight'                 # 弹出位置 可选值：topRight, bottomRight, bottomLeft, topLeft, topCenter, bottomCenter, center
    transitionIn: 'bounceInLeft'         # 弹窗打开动画 可选值：bounceInLeft, bounceInRight, bounceInUp, bounceInDown, fadeIn, fadeInDown, fadeInUp, fadeInLeft, fadeInRight, flipInX
    transitionOut: 'fadeOutRight'        # 弹窗关闭动画 可选值：fadeOut, fadeOutUp, fadeOutDown, fadeOutLeft, fadeOutRight, flipOutX
    titleColor: 'var(--color-text)'      # 标题颜色
    messageColor: 'var(--color-text)'    # 消息颜色
    backgroundColor: 'var(--color-card)' # 默认背景色
    zindex: 2147483647                   # 层级
    copyright:                           # 是否在复制时弹出版权提示，影响范围：ctrl+c、代码块复制按钮、右键复制选项
      enable: true
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'far fa-copyright light-blue'
    aplayer:                              # 是否开启音乐通知；播放、暂停、失败 时的图标
      enable: true
      play: fa-solid fa-play
      pause: fa-solid fa-pause
    rightmenu:
      enable: true                        # 是否开启右键模块的消息通知
      notice: true                        # 唤醒原右键菜单的通知  
    
music:
  class: music
  display: [desktop, mobile] # [desktop, mobile]
  pjaxReload: false
